/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package almacen;

import Modelos.Usuario;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.LayoutStyle;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;
import servicios.*;

/**
 *
 * @author H-P
 */
public class JPanelUsuarios extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    
    TableCellRendererColor tbc =new TableCellRendererColor();
    ServicioUsuarios servicios;
    listarTablas listTabla;
    ArrayList<Usuario> usuarios;
    public JPanelUsuarios() {
        initComponents();
        init();
    }
    
    private void init(){
        servicios=new ServicioUsuarios();
        listTabla=new listarTablas();
        usuarios=servicios.getUsuarios();
        tbc.pintarTabla(jTableUsuarios);
        listTabla.tablaUsuario(usuarios,jTableUsuarios);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        GridBagConstraints gridBagConstraints;

        jPanel1 = new JPanel();
        jButton1 = new JButton();
        jPanel4 = new JPanel();
        jLabel1 = new JLabel();
        jPanel2 = new JPanel();
        jScrollPane1 = new JScrollPane();
        jTableUsuarios = new JTable();
        jPanel3 = new JPanel();
        btnEditar = new JButton();
        jButton3 = new JButton();
        jPanel5 = new JPanel();
        jPanel6 = new JPanel();
        jLabel2 = new JLabel();
        jButton4 = new JButton();

        jPanel1.setBackground(new Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);

        jButton1.setBackground(new Color(255, 153, 51));
        jButton1.setIcon(new ImageIcon(getClass().getResource("/imagenes/1486485588-add-create-new-math-sign-cross-plus_81186.png"))); // NOI18N
        jButton1.setText("NUEVO");
        jButton1.setBorder(new LineBorder(new Color(255, 255, 255), 5, true));
        jButton1.setBorderPainted(false);
        jButton1.setFocusable(false);
        jButton1.setMaximumSize(null);
        jButton1.setMinimumSize(new Dimension(125, 41));
        jButton1.setPreferredSize(new Dimension(125, 41));
        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new Color(255, 255, 255));
        jPanel4.setLayout(new GridBagLayout());

        jLabel1.setFont(new Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("USUARIOS");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(39, 27, 32, 27);
        jPanel4.add(jLabel1, gridBagConstraints);

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setBackground(new Color(51, 0, 51));
        setAutoscrolls(true);
        setFont(new Font("Tahoma", 0, 18)); // NOI18N
        setInheritsPopupMenu(true);
        setLayout(new BorderLayout());

        jPanel2.setBackground(new Color(255, 255, 255));
        jPanel2.setLayout(new BorderLayout());

        jTableUsuarios.setFont(new Font("Tahoma", 0, 18)); // NOI18N
        jTableUsuarios.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CDGO", "NOMBRES", "APELLIDOS", "CORREO", "CARGO"
            }
        ) {
            Class[] types = new Class [] {
                Integer.class, String.class, String.class, String.class, String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableUsuarios.setRowHeight(28);
        jScrollPane1.setViewportView(jTableUsuarios);

        jPanel2.add(jScrollPane1, BorderLayout.CENTER);

        add(jPanel2, BorderLayout.CENTER);

        jPanel3.setBackground(new Color(255, 255, 255));

        btnEditar.setBackground(new Color(255, 153, 51));
        btnEditar.setText("EDITAR");
        btnEditar.setPreferredSize(new Dimension(89, 40));
        btnEditar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jButton3.setBackground(new Color(255, 153, 51));
        jButton3.setText("ELIMINAR");
        jButton3.setPreferredSize(new Dimension(105, 41));
        jButton3.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(746, Short.MAX_VALUE)
                .addComponent(btnEditar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        add(jPanel3, BorderLayout.PAGE_END);

        jPanel5.setBackground(new Color(255, 255, 255));
        jPanel5.setAutoscrolls(true);

        jPanel6.setBackground(new Color(255, 255, 255));
        jPanel6.setLayout(new GridBagLayout());

        jLabel2.setFont(new Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("USUARIOS");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(39, 27, 32, 27);
        jPanel6.add(jLabel2, gridBagConstraints);

        jButton4.setBackground(new Color(255, 153, 51));
        jButton4.setIcon(new ImageIcon(getClass().getResource("/imagenes/1486485588-add-create-new-math-sign-cross-plus_81186.png"))); // NOI18N
        jButton4.setText("NUEVA ");
        jButton4.setAutoscrolls(true);
        jButton4.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        GroupLayout jPanel5Layout = new GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(815, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(24, 24, 24))
        );
        jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        add(jPanel5, BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFrameFormularioUsuario jFrameFormularioUsuario = new JFrameFormularioUsuario();
        jFrameFormularioUsuario.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(jTableUsuarios.getSelectedRow()<0){            
            JOptionPane.showMessageDialog(null, "Debes seleccionar una fila de la tabla");
        } else {
            System.out.println("almacen.JPanelUsuarios.jButton3ActionPerformed()");
            JFrameFormularioUsuario jFrameFormularioUsuario = new JFrameFormularioUsuario();
            jFrameFormularioUsuario.cargarDatos(3, "ffuk", "yrtiurtr", "gj", "giygi", "gj", "ugiyj");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JFrameFormularioUsuario jFrameFormularioUsuario = new JFrameFormularioUsuario();
        jFrameFormularioUsuario.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnEditarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    JButton btnEditar;
    JButton jButton1;
    JButton jButton3;
    JButton jButton4;
    JLabel jLabel1;
    JLabel jLabel2;
    JPanel jPanel1;
    JPanel jPanel2;
    JPanel jPanel3;
    JPanel jPanel4;
    JPanel jPanel5;
    JPanel jPanel6;
    JScrollPane jScrollPane1;
    public static JTable jTableUsuarios;
    // End of variables declaration//GEN-END:variables
}
